apiVersion: apps/v1
kind: Deployment
metadata:
  name: social
  labels:
    app: social
spec:
  replicas: 1
  selector:
    matchLabels:
      app: social
  template:
    metadata:
      labels:
        app: social
    spec:
      containers:
        - name: social
          image: socialbeats/social:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3004
          envFrom:
            - configMapRef:
                name: social-config
            - secretRef:
                name: social-secret
