apiVersion: v1
kind: Secret
metadata:
  name: social-secret
  namespace: socialbeats
type: Opaque
stringData:
  MONGOADMIN: "${SOCIAL_MONGOADMIN}"
  MONGOPASS: "${SOCIAL_MONGOPASS}"
  JWT_SECRET: "${SOCIAL_JWT_SECRET}"
