apiVersion: v1
kind: Secret
metadata:
  name: mongo-payments-and-suscription-secret
  namespace: socialbeats
type: Opaque
stringData:
  MONGOADMIN: "${MONGO_PAYMENTS_MONGOADMIN}"
  MONGOPASS: "${MONGO_PAYMENTS_MONGOPASS}"
