apiVersion: v1
kind: Service
metadata:
  name: mongo-payments-and-suscription
  namespace: socialbeats
spec:
  clusterIP: None
  selector:
    app: mongo-payments-and-suscription
  ports:
    - port: 27017
      targetPort: 27017
