apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-auth
  namespace: socialbeats
  labels:
    app: user-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-auth
  template:
    metadata:
      labels:
        app: user-auth
    spec:
      containers:
      - name: user-auth
        image: socialbeats/user-auth:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 3001
        envFrom:
          - configMapRef:
              name: user-auth-config
          - secretRef:
              name: user-auth-secret
        resources:
          requests:
            cpu: "150m"
            memory: "256Mi"
          limits:
            cpu: "800m"
            memory: "512Mi"