apiVersion: v1
kind: Secret
metadata:
  name: user-auth-secret
type: Opaque
stringData:
  JWT_SECRET: "dev_secret_change_in_production"
  JWT_ACCESS_EXPIRY: "15m"
  JWT_REFRESH_EXPIRY: "7"
  REDIS_PASSWORD: ""
  MONGOADMIN: ""
  MONGOPASS: ""
