apiVersion: v1
kind: Secret
metadata:
  name: user-auth-secret
  namespace: socialbeats
type: Opaque
stringData:
  JWT_SECRET: "${USER_AUTH_JWT_SECRET}"
  JWT_ACCESS_EXPIRY: "${USER_AUTH_JWT_ACCESS_EXPIRY}"
  JWT_REFRESH_EXPIRY: "${USER_AUTH_JWT_REFRESH_EXPIRY}"
  REDIS_PASSWORD: "${USER_AUTH_REDIS_PASSWORD}"
  MONGOADMIN: "${USER_AUTH_MONGOADMIN}"
  MONGOPASS: "${USER_AUTH_MONGOPASS}"
  DEFAULT_ADMIN_USERNAME: "${USER_AUTH_DEFAULT_ADMIN_USERNAME}"
  DEFAULT_ADMIN_EMAIL: "${USER_AUTH_DEFAULT_ADMIN_EMAIL}"
  DEFAULT_ADMIN_PASSWORD: "${USER_AUTH_DEFAULT_ADMIN_PASSWORD}"
  DO_SPACES_KEY: "${USER_AUTH_DO_SPACES_KEY}"
  DO_SPACES_SECRET: "${USER_AUTH_DO_SPACES_SECRET}"
  DO_SPACES_BUCKET: "${USER_AUTH_DO_SPACES_BUCKET}"
  DO_SPACES_ENDPOINT: "${USER_AUTH_DO_SPACES_ENDPOINT}"
  DO_SPACES_REGION: "${USER_AUTH_DO_SPACES_REGION}"
  DO_SPACES_CDN_ENDPOINT: "${USER_AUTH_DO_SPACES_CDN_ENDPOINT}"
  INTERNAL_API_KEY: "${USER_AUTH_INTERNAL_API_KEY}"
  RESEND_API_KEY: "${USER_AUTH_RESEND_API_KEY}"
  EMAIL_FROM: "${USER_AUTH_EMAIL_FROM}"
  APP_NAME: "${USER_AUTH_APP_NAME}"
  FRONTEND_URL: "${USER_AUTH_FRONTEND_URL}" 
  PAYMENTS_SERVICE_URL: "${USER_AUTH_PAYMENTS_SERVICE_URL}"
  SPACE_URL:  "{USER_AUTH_SPACE_URL}"
  SPACE_API_KEY: "{USER_AUTH_SPACE_API_KEY}"