apiVersion: v1
kind: Secret
metadata:
  name: user-auth-secret
type: Opaque
stringData:
  JWT_SECRET: "${USER_AUTH_JWT_SECRET}"
  JWT_ACCESS_EXPIRY: "${USER_AUTH_JWT_ACCESS_EXPIRY}"
  JWT_REFRESH_EXPIRY: "${USER_AUTH_JWT_REFRESH_EXPIRY}"
  REDIS_PASSWORD: "${USER_AUTH_REDIS_PASSWORD}"
  MONGOADMIN: "${USER_AUTH_MONGOADMIN}"
  MONGOPASS: "${USER_AUTH_MONGOPASS}"
