apiVersion: apps/v1
kind: Deployment
metadata:
  name: space-nginx
  namespace: socialbeats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: space-nginx
  template:
    metadata:
      labels:
        app: space-nginx
    spec:
      containers:
        - name: space-nginx
          image: socialbeats/space-nginx:1.0.0
          ports:
            - containerPort: 5403
          volumeMounts:
            - name: space-statics
              mountPath: /usr/share/nginx/html
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: space-statics
          persistentVolumeClaim:
            claimName: space-statics
        - name: nginx-config
          configMap:
            name: space-nginx-config