apiVersion: v1
kind: ConfigMap
metadata:
  name: beats-upload-config
  namespace: socialbeats
data:
  NODE_ENV: "production"
  PORT: "3005"
  LOG_LEVEL: "info"
  API_TITLE: "Beats upload microservice API"
  API_DESCRIPTION: "This is an OAS description of beats upload REST API"
  MONGOURL: "mongodb://mongo-beats-upload-0.mongo-beats-upload:27017/microservice-beats-upload"
  MONGOTESTURL: "mongodb://mongo-beats-upload-0.mongo-beats-upload:27017/microservice-beats-upload_test"
