apiVersion: v1
kind: Secret
metadata:
  name: beats-upload-secret
  namespace: socialbeats
type: Opaque
stringData:
  MONGOADMIN: "${BEATS_UPLOAD_MONGOADMIN}"
  MONGOPASS: "${BEATS_UPLOAD_MONGOPASS}"
  JWT_SECRET: "${BEATS_UPLOAD_JWT_SECRET}"
  AWS_REGION: "${BEATS_UPLOAD_AWS_REGION}"
  AWS_ACCESS_KEY_ID: "${BEATS_UPLOAD_AWS_ACCESS_KEY_ID}"
  AWS_SECRET_ACCESS_KEY: "${BEATS_UPLOAD_AWS_SECRET_ACCESS_KEY}"
  AWS_BUCKET_NAME: "${BEATS_UPLOAD_AWS_BUCKET_NAME}"
  CDN_DOMAIN: "${BEATS_UPLOAD_CDN_DOMAIN}"
