apiVersion: v1
kind: Secret
metadata:
  name: beats-upload-secret
type: Opaque
stringData:
  MONGOADMIN: ""
  MONGOPASS: ""
  JWT_SECRET: ""
  AWS_REGION: ""
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_BUCKET_NAME: ""
  CDN_DOMAIN: ""
