apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: socialbeats
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: api-nginx
  rules:
  - host: app.localhost
    http:
      paths:
      - path: /socialbeats
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
