apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-config
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;
        
        location /socialbeats {
            alias /usr/share/nginx/html;
            index index.html index.htm;
            try_files $uri $uri/ /socialbeats/index.html;
        }
        
        location / {
            return 404;
        }
        
        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root /usr/share/nginx/html;
        }
    }