apiVersion: v1
kind: Secret
metadata:
  name: frontend-secrets
  namespace: socialbeats
type: Opaque
stringData:
  VITE_BASE_URL: "${FRONTEND_VITE_BASE_URL}"
  VITE_CDN_DOMAIN: "${FRONTEND_VITE_CDN_DOMAIN}"
