apiVersion: v1
kind: Secret
metadata:
  name: frontend-secrets
  namespace: socialbeats
type: Opaque
stringData:
  VITE_BASE_URL: "${FRONTEND_VITE_BASE_URL}"
  VITE_CDN_DOMAIN: "${FRONTEND_VITE_CDN_DOMAIN}"
  VITE_SPACE_URL: "${FRONTEND_VITE_SPACE_URL}"
  VITE_SPACE_API_KEY: "${FRONTEND_VITE_SPACE_API_KEY}"
  VITE_ANALYTICS_SERVICE_URL: "${FRONTEND_VITE_ANALYTICS_SERVICE_URL}"