apiVersion: v1
kind: Secret
metadata:
  name: frontend-secrets
type: Opaque
stringData:
  VITE_BASE_URL: "http://user-auth.default.svc.cluster.local:3000/api/v1"
  VITE_CDN_DOMAIN: "s3-cdn-server-for-retrieving-files"
