apiVersion: v1
kind: Secret
metadata:
  name: mongo-beats-interaction-secret
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "${MONGO_BEATS_INTERACTION_MONGO_INITDB_ROOT_USERNAME}"
  MONGO_INITDB_ROOT_PASSWORD: "${MONGO_BEATS_INTERACTION_MONGO_INITDB_ROOT_PASSWORD}"
