apiVersion: v1
kind: Service
metadata:
  name: mongo-beats-interaction
  namespace: socialbeats
spec:
  selector:
    app: mongo-beats-interaction
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
