apiVersion: v1
kind: Secret
metadata:
  name: mongo-user-auth-secret
  namespace: socialbeats
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER_AUTH_MONGO_INITDB_ROOT_USERNAME}"
  MONGO_INITDB_ROOT_PASSWORD: "${MONGO_USER_AUTH_MONGO_INITDB_ROOT_PASSWORD}"
