apiVersion: v1
kind: Secret
metadata:
  name: mongo-beats-upload-secret
  namespace: socialbeats
type: Opaque
stringData:
  MONGOADMIN: "${MONGO_BEATS_UPLOAD_MONGOADMIN}"
  MONGOPASS: "${MONGO_BEATS_UPLOAD_MONGOPASS}"