apiVersion: v1
kind: ConfigMap
metadata:
  name: beats-interaction-config
  namespace: socialbeats
data:
  NODE_ENV: "production"
  PORT: "3002"
  LOG_LEVEL: "info"
  API_TITLE: "beats-interaction microservice API"
  API_DESCRIPTION: "This is an OAS description of this beats-interaction microservice REST API"
  MONGOURL: "mongodb://mongo-beats-interaction:27017/beats-interaction"
  KAFKA_CONNECTION_MAX_RETRIES: "10"
  KAFKA_CONNECTION_RETRY_DELAY: "3000"
  KAFKA_COOLDOWN: "30000"
  KAFKA_BROKER: "kafka:9092"
  ENABLE_KAFKA: "true"
  ENABLE_REDIS: "true"
  REDIS_HOST: "beats-interaction-redis"
  REDIS_PORT: "6379"
  REDIS_CONNECTION_MAX_RETRIES: "5"
  REDIS_CONNECTION_RETRY_DELAY: "2000"
  REDIS_COOLDOWN: "30000"
  ENABLE_PRICING: "true"