apiVersion: v1
kind: Secret
metadata:
  name: beats-interaction-secret
  namespace: socialbeats
type: Opaque
stringData:
  MONGOADMIN: "${BEATS_INTERACTION_MONGOADMIN}"
  MONGOPASS: "${BEATS_INTERACTION_MONGOPASS}"
  JWT_SECRET: "${BEATS_INTERACTION_JWT_SECRET}"
  OPENROUTER_API_KEY: "${BEATS_INTERACTION_OPENROUTER_API_KEY}"
  INTERNAL_API_KEY: "${BEATS_INTERACTION_INTERNAL_API_KEY}"
