apiVersion: v1
kind: Secret
metadata:
  name: beats-interaction-secret
type: Opaque
stringData:
  MONGOADMIN: "${BEATS_INTERACTION_MONGOADMIN}"
  MONGOPASS: "${BEATS_INTERACTION_MONGOPASS}"
  JWT_SECRET: "${BEATS_INTERACTION_JWT_SECRET}"
