apiVersion: v1
kind: Service
metadata:
  name: beats-interaction
  namespace: socialbeats
spec:
  selector:
    app: beats-interaction
  type: ClusterIP
  ports:
    - port: 3002
      targetPort: 3002
