apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  NODE_ENV: "production"
  PORT: "3000"
  LOG_LEVEL: "debug"
  ALLOWED_ORIGINS: "http://localhost:3001,http://localhost:3002,http://localhost:3003,http://localhost:3004,http://localhost:3005,http://localhost:3006,http://localhost:3007,http://localhost:5173"
  USERS_SERVICE_URL: "http://user-auth:3001"
  BEATS_INTERACTION_SERVICE_URL: "http://beats-interaction:3002"
  ANALYTICS_SERVICE_URL: "http://analytics-and-dashboards:3003"
  SOCIAL_SERVICE_URL: "http://social:3004"
  BEATS_SERVICE_URL: "http://beats-upload:3005"
  NOTIFICATIONS_SERVICE_URL: "http://notifications:3007"
  PAYMENTS_SERVICE_URL: "http://beats-interaction:3006"
