apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  NODE_ENV: "production"
  PORT: "3000"
  LOG_LEVEL: "debug"
  USERS_SERVICE_URL: "http://user-auth:3001"
  BEATS_INTERACTION_SERVICE_URL: "http://beats-interaction:3002"
  ANALYTICS_SERVICE_URL: "http://analytics-and-dashboards:3003"
  SOCIAL_SERVICE_URL: "http://social:3004"
  BEATS_SERVICE_URL: "http://beats-upload:3005"
  PAYMENTS_SERVICE_URL: "http://beats-interaction:3006"
  NOTIFICATIONS_SERVICE_URL: "http://notifications:3007"
  SPACE_SERVICE_URL: "http://space-nginx:5403"
