apiVersion: v1
kind: Secret
metadata:
  name: space-mongodb-secret
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "${SPACE_MONGO_DB_MONGO_INITDB_ROOT_USERNAME}"
  MONGO_INITDB_ROOT_PASSWORD: "${SPACE_MONGO_DB_MONGO_INITDB_ROOT_PASSWORD}"
  DATABASE_NAME: "${SPACE_MONGO_DB_DATABASE_NAME}"
  DATABASE_USERNAME: "${SPACE_MONGO_DB_DATABASE_USERNAME}"
  DATABASE_PASSWORD: "${SPACE_MONGO_DB_DATABASE_PASSWORD}"
