apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-and-suscription
  namespace: socialbeats
  labels:
    app: payments-and-suscription
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-and-suscription
  template:
    metadata:
      labels:
        app: payments-and-suscription
    spec:
      containers:
        - name: payments-and-suscription
          image: socialbeats/payments-and-suscriptions:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3006
          envFrom:
            - configMapRef:
                name: payments-and-suscription-config
            - secretRef:
                name: payments-and-suscription-secret
          resources:
            requests:
              cpu: "150m"
              memory: "256Mi"
            limits:
              cpu: "800m"
              memory: "512Mi"
