apiVersion: v1
kind: Secret
metadata:
  name: payments-and-suscription-secret
  namespace: socialbeats
type: Opaque
stringData:
  MONGOADMIN: "${PAYMENTS_MONGOADMIN}"
  MONGOPASS: "${PAYMENTS_MONGOPASS}"
  JWT_SECRET: "${PAYMENTS_JWT_SECRET}"
  FRONTEND_URL: "${PAYMENTS_FRONTEND_URL}"
  SPACE_URL: "${PAYMENTS_SPACE_URL}"
  STRIPE_SECRET_KEY: "${PAYMENTS_STRIPE_SECRET_KEY}"
  STRIPE_PUBLISHABLE_KEY: "${PAYMENTS_STRIPE_PUBLISHABLE_KEY}"
  STRIPE_PRICE_FREE: "${PAYMENTS_STRIPE_PRICE_FREE}"
  STRIPE_PRICE_PRO: "${PAYMENTS_STRIPE_PRICE_PRO}"
  STRIPE_PRICE_STUDIO: "${PAYMENTS_STRIPE_PRICE_STUDIO}"
  STRIPE_PRICE_ADDON_DECORATIVES: "${PAYMENTS_STRIPE_PRICE_ADDON_DECORATIVES}"
  STRIPE_PRICE_ADDON_PROMOTED_BEAT: "${PAYMENTS_STRIPE_PRICE_ADDON_PROMOTED_BEAT}"
  STRIPE_PRICE_ADDON_EXTRA_DASHBOARD: "${PAYMENTS_STRIPE_PRICE_ADDON_EXTRA_DASHBOARD}"
  SPACE_API_KEY: "${PAYMENTS_SPACE_API_KEY}"
  INTERNAL_API_KEY: "${PAYMENTS_INTERNAL_API_KEY}"