apiVersion: v1
kind: Secret
metadata:
  name: mongo-social-secret
  namespace: socialbeats
type: Opaque
stringData:
  MONGOADMIN: "${MONGO_SOCIAL_MONGOADMIN}"
  MONGOPASS: "${MONGO_SOCIAL_MONGOPASS}"
